[package]
name = "our-std-proc-macro"
edition = "2018"
version = "0.0.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"

