[package]
authors = ['Compound <https://compound.finance>']
description = 'Pallet for implementing CASH.'
edition = '2018'
homepage = 'https://compound.cash'
name = 'runtime-interfaces'
repository = 'https://github.com/compound-finance/compound-chain/'
version = '1.0.0'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-runtime-interface = {version="2.0.0", default-features=false}
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
lazy_static = "1.4.0"

[features]
default = ['std']
std = [
    "sp-runtime-interface/std",
    "codec/std"
]
