[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/cash',
    'pallets/runtime-interfaces',
    'runtime',
    'std',
    'compound-crypto',
    'ethereum-client',
    'test-utils/open-oracle-mock-reporter',
    'trx-request'
]
