[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/cash',
    'pallets/runtime-interfaces',
    'runtime',
    'std',
    'compound-crypto',
    'open-oracle-mock-reporter'
]
