[package]
name = "trx-request"
version = "0.1.0"
authors = ['Compound <https://compound.finance>']
edition = "2018"

[dependencies]
logos = "0.12"
hex = "0.4.2"

sp-core = { default-features = false, features = ['full_crypto'], git = 'https://github.com/compound-finance/substrate', branch = 'jflatow/compound' }

our-std = { path = '../our-std', default-features = false }

[features]
