[package]
authors = ['Compound <https://compound.finance>']
description = 'Pallet for implementing CASH.'
edition = '2018'
homepage = 'https://compound.cash'
name = 'pallet-cash'
repository = 'https://github.com/compound-finance/compound-chain/'
version = '1.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }
runtime-interfaces = { default-features = false, version = '1.0.0', path="../runtime-interfaces"}
ethereum-client = { path="../../ethereum_client", version="0.1.0", default-features = false}
sp-std = { version = "2.0.0", default-features = false }
sp-runtime = { default-features = false, version = '2.0.0' }

[dev-dependencies]
sp-core = { default-features = false, version = '2.0.0' }
sp-io = { version = "2.0.0", default-features = false, features = ["disable_oom", "disable_panic_handler"] }


[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-std/std',
    'runtime-interfaces/std',
    'sp-io/std',
]
