[package]
authors = ['Compound <https://compound.finance>']
description = 'Pallet for implementing CASH.'
edition = '2018'
homepage = 'https://compound.cash'
name = 'pallet-cash'
repository = 'https://github.com/compound-finance/compound-chain/'
version = '1.0.0'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '1.3.4', default-features = false, features = ['derive'] }
frame-support = { default-features = false, version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
frame-system = { default-features = false, version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-core = { default-features = false, version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-io = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git', features = ["disable_oom", "disable_panic_handler"]}
sp-runtime = { default-features = false, version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-std = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }

runtime-interfaces = { path = '../runtime-interfaces', version = '1.0.0', default-features = false }

num-bigint = { default-features = false, version = "0.3" }
num-traits = { default-features = false, version = "0.2" }
anyhow = { version = "1.0", default-features = false }

ethereum-client = { path = "../../ethereum_client", version = '0.1.0', default-features = false}

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-std/std',
    'runtime-interfaces/std',
    'sp-io/std',
    'sp-core/std',
]
