[package]
authors = ['Compound <https://compound.finance>']
description = 'Pallet for implementing CASH.'
edition = '2018'
homepage = 'https://compound.cash'
name = 'pallet-cash'
repository = 'https://github.com/compound-finance/compound-chain/'
version = '1.0.0'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '1.3.4', default-features = false, features = ['derive'] }
frame-support = { default-features = false, version = '2.0.0', path = '../../../substrate/frame/support' }
frame-system = { default-features = false, version = '2.0.0', path = '../../../substrate/frame/system' }
runtime-interfaces = { default-features = false, version = '1.0.0', path='../runtime-interfaces'}
sp-io = { version = '2.0.0', default-features = false, path='../../../substrate/primitives/io' }

[dev-dependencies]
sp-core = { default-features = false, version = '2.0.0', path = '../../../substrate/primitives/core' }
sp-runtime = { default-features = false, version = '2.0.0' }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'runtime-interfaces/std',
		'sp-io/std'
]
