
- hosts:
    - authority_node
  tasks:
    - name: add babe author key to keystore
      uri:
        url: http://localhost:9933
        method: "POST"
        body_format: json
        body: |
            {
                "jsonrpc":"2.0",
                "id":1,
                "method":"author_insertKey",
                "params": [
                    "babe",
                    "{{ mnemonic }}",
                    "{{ babe_public_key }}"
                ]
            }
      register: babe_insertion
      until: babe_insertion.status == 200
      retries: 10
      delay: 5

    - name: show babe erpsonse
      debug:
        var: babe_insertion

    - name: add grandpa author key to keystore
      uri:
        url: http://localhost:9933
        method: "POST"
        body_format: json
        body: |
            {
                "jsonrpc":"2.0",
                "id":1,
                "method":"author_insertKey",
                "params": [
                    "gran",
                    "{{ mnemonic }}",
                    "{{ grandpa_public_key }}"
                ]
            }
      register: insertion
      until: insertion.status == 200
      retries: 10
      delay: 5

    - name: show erpsonse
      debug:
        var: insertion

