[package]
authors = ['Compound <https://compound.finance>']
edition = '2018'
homepage = 'https://compound.cash'
name = 'compound-chain-runtime'
repository = 'https://github.com/compound-finance/compound-chain/'
version = '1.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { version = '3.0.0', git = 'https://github.com/compound-finance/substrate.git' }

[dependencies]
codec = { package = 'parity-scale-codec', version = '1.3.4', default-features = false, features = ['derive'] }

hex-literal = { optional = true, version = '0.3.1' }
serde = { features = ['derive'], optional = true, version = '1.0.101' }

# Substrate dependencies
frame-executive = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
frame-support = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
frame-system = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
frame-system-rpc-runtime-api = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }

sp-api = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
sp-block-builder = { git = 'https://github.com/compound-finance/substrate.git', default-features = false, version = '2.0.0'}
sp-consensus-babe = { version = '0.8.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
sp-core = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
sp-inherents = { git = 'https://github.com/compound-finance/substrate.git', default-features = false, version = '2.0.0'}
sp-offchain = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
sp-runtime = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
sp-session = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
sp-std = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
sp-transaction-pool = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
sp-version = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }

# Used only for runtime benchmarking
frame-benchmarking = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git', optional = true }
frame-system-benchmarking = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git', optional = true }

# Other pallets
pallet-babe = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
pallet-balances = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
pallet-grandpa = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
pallet-randomness-collective-flip = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
pallet-sudo = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
pallet-timestamp = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
pallet-transaction-payment = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
pallet-transaction-payment-rpc-runtime-api = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }
pallet-session = { version = '2.0.0', default-features = false, git = 'https://github.com/compound-finance/substrate.git' }

# Local dependencies
pallet-cash = { path = '../pallets/cash', default-features = false, version = '1.0.0' }

[features]
default = ['std']
runtime-benchmarks = [
    'hex-literal',
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking',
    'frame-system/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
]
std = [
    'codec/std',
    'frame-executive/std',
    'frame-support/std',
    'frame-system-rpc-runtime-api/std',
    'frame-system/std',
    'pallet-babe/std',
    'pallet-balances/std',
    'pallet-cash/std',
    'pallet-grandpa/std',
    'pallet-randomness-collective-flip/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'pallet-transaction-payment/std',
    'pallet-session/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-babe/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
]
