
- name: install Compound Chain systemd unit file (authority node)
  template: src=compound-chain-authority-node.j2 dest=/etc/systemd/system/compound-chain.service
  become: true
  when: "'authority_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] | union(groups['full_node']) | difference([inventory_hostname]) }}"
  tags:
    compound-service

- name: install Compound Chain systemd unit file (full node)
  template: src=compound-chain-full-node.j2 dest=/etc/systemd/system/compound-chain.service
  become: true
  when: "'full_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] | union(groups['full_node']) | difference([inventory_hostname]) }}"
  tags:
    compound-service

- name: start Compound Chain Authority Node
  systemd: state={{ compound_service_state }} name=compound-chain daemon_reload=yes
  become: true
  tags:
    compound-service
