
- name: install Gateway systemd unit file (authority node)
  template: src=gateway-authority-node.j2 dest=/etc/systemd/system/gateway.service
  become: true
  when: "'authority_node' in group_names"
  vars:
    peers: "{{ vars.bootnodes }}"
  tags:
    gateway-service

- name: install Gateway systemd unit file (full node)
  template: src=gateway-full-node.j2 dest=/etc/systemd/system/gateway.service
  become: true
  when: "'full_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] }}"
  tags:
    gateway-service

- name: start Gateway Authority Node
  systemd: state={{ gateway_service_state }} name=gateway daemon_reload=yes
  become: true
  tags:
    gateway-service
