
- name: stop compound chain service
  become: true
  systemd:
    name: compound-chain.service
    state: stopped

- name: bring chain spec
  become: true
  ansible.builtin.copy:
    src: "{{ chain_spec }}"
    dest: "{{ compound_user_home }}/chainSpec.json"
    owner: compound
    mode: '0644'

- name: purge chain
  become: true
  shell: |
    set -o pipefail
    {{ compound_chain_bin }} purge-chain -y --chain "{{ compound_user_home }}/chainSpec.json" --base-path {{ chain_data_dir }}  --database paritydb
  args:
    executable: /bin/bash
  changed_when: False

- name: reinstall Compound Chain systemd unit file (authority node)
  template: src=compound-chain-authority-node.j2 dest=/etc/systemd/system/compound-chain.service
  become: true
  when: "'authority_node' in group_names"
  vars:
    peers: "{{ bootnodes }}"
    authority: "{{ authority }}"
  tags:
    compound-service

- name: reinstall Compound Chain systemd unit file (full node)
  template: src=compound-chain-full-node.j2 dest=/etc/systemd/system/compound-chain.service
  become: true
  when: "'full_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] }}"
  tags:
    compound-service

- name: start compound chain service
  become: true
  systemd:
    name: compound-chain.service
    state: started
    daemon_reload: yes