
- name: stop gateway service
  become: true
  systemd:
    name: gateway.service
    state: stopped

# chainspecs have gotten much more stable
# - name: bring chain spec
#   become: true
#   ansible.builtin.copy:
#     src: "{{ chain_spec }}"
#     dest: "{{ gateway_chain_spec_raw }}"
#     owner: gateway
#     mode: '0644'

- name: purge chain
  become: true
  shell: |
    set -o pipefail
    {{ gateway_bin }} purge-chain -y --chain {{ gateway_chain_spec_raw }} --base-path {{ chain_data_dir }}  --database paritydb-experimental
  args:
    executable: /bin/bash
  changed_when: False

- name: reinstall Gateway systemd unit file (authority node)
  template: src=gateway-authority-node.j2 dest=/etc/systemd/system/gateway.service
  become: true
  when: "'authority_node' in group_names"
  vars:
    peers: "{{ bootnodes }}"
    authority: "{{ authority }}"
  tags: gateway-service

- name: reinstall Gateway systemd unit file (full node)
  template: src=gateway-full-node.j2 dest=/etc/systemd/system/gateway.service
  become: true
  when: "'full_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] }}"
  tags: gateway-service

- name: start gateway service
  become: true
  systemd:
    name: gateway.service
    state: started
    daemon_reload: yes
