[package]
authors = ['Compound <https://compound.finance>']
build = 'build.rs'
description = 'A Compound Chain node.'
edition = '2018'
homepage = 'https://compound.cash'
name = 'compound-chain'
repository = 'https://github.com/compound-finance/compound-chain/'
version = '1.0.0'

[[bin]]
name = 'compound-chain'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = { version = '2.0.0', path = '../../substrate/utils/build-script-utils' }

[dependencies]
jsonrpc-core = '15.0.0'
structopt = '0.3.8'

serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"

# Local Dependencies
compound-chain-runtime = { version = '1.0.0', path = '../runtime' }
runtime-interfaces = { path = '../pallets/runtime-interfaces', version = '1.0.0' }

# Substrate dependencies
sc-cli = { version = '0.8.0', path = '../../substrate/client/cli', features = ['wasmtime'] }
sp-core = { version = '2.0.0', path = '../../substrate/primitives/core' }
sc-executor = { version = '0.8.0', path = '../../substrate/client/executor', features = ['wasmtime'] }
sc-service = { version = '0.8.0', path = '../../substrate/client/service', default-features=false, features = [] }
sp-inherents = { version = '2.0.0', path = '../../substrate/primitives/inherents' }
sc-transaction-pool = { version = '2.0.0', path = '../../substrate/client/transaction-pool' }
sp-transaction-pool = { version = '2.0.0', path = '../../substrate/primitives/transaction-pool' }
sc-consensus-aura = { version = '0.8.0', path = '../../substrate/client/consensus/aura' }
sp-consensus-aura = { version = '0.8.0', path = '../../substrate/primitives/consensus/aura' }
sp-consensus = { version = '0.8.0', path = '../../substrate/primitives/consensus/common' }
sc-consensus = { version = '0.8.0', path = '../../substrate/client/consensus/common' }
sc-finality-grandpa = { version = '0.8.0', path = '../../substrate/client/finality-grandpa' }
sp-finality-grandpa = { version = '2.0.0', path = '../../substrate/primitives/finality-grandpa' }
sc-client-api = { version = '2.0.0', path = '../../substrate/client/api' }
sp-runtime = { version = '2.0.0', path = '../../substrate/primitives/runtime' }

# These dependencies are used for the node template's RPCs
sc-rpc = { version = '2.0.0', path = '../../substrate/client/rpc' }
sp-api = { version = '2.0.0', path = '../../substrate/primitives/api' }
sc-rpc-api = { version = '0.8.0', path = '../../substrate/client/rpc-api' }
sp-blockchain = { version = '2.0.0', path = '../../substrate/primitives/blockchain' }
sp-chain-spec = { version = '2.0.0', path = '../../substrate/primitives/chain-spec' }
sp-block-builder = { version = '2.0.0', path = '../../substrate/primitives/block-builder' }
sc-basic-authorship = { version = '0.8.0', path = '../../substrate/client/basic-authorship' }
substrate-frame-rpc-system = { version = '2.0.0', path = '../../substrate/utils/frame/rpc/system' }
pallet-transaction-payment-rpc = { version = '2.0.0', path = '../../substrate/frame/transaction-payment/rpc/' }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = '2.0.0', path = '../../substrate/frame/benchmarking' }
frame-benchmarking-cli = { version = '2.0.0', path = '../../substrate/utils/frame/benchmarking-cli', default-features=false, optional=true }

[features]
default = []
runtime-benchmarks = [
	'compound-chain-runtime/runtime-benchmarks',
	'frame-benchmarking-cli',
]
