
- hosts: authority_node
  vars:
    rustup_init_url: https://sh.rustup.rs
    ssh_home: "{{ ansible_env.HOME }}/.ssh"
    git_deploy_key: "{{ ssh_home }}/id_rsa_compound_chain_deploy"
    cargo_home: "{{ ansible_env.HOME }}/.cargo"
    cargo_bin: "{{ cargo_home }}/bin/cargo"
    rustup_home: "{{ cargo_home }}/bin/rustup"
    compound_chain_home: "{{ ansible_env.HOME }}/compound_chain"
    git_repo: "ssh://git@github.com/compound-finance/compound-chain.git"
    git_branch: "master"

  tasks:
    - name: Add Deploy Key
      copy:
        src:  '{{ deploy_key }}'
        dest: '{{ git_deploy_key }}'
        owner: ubuntu
        group: ubuntu
        mode: '0400'

    - name: Checkout Compound Chain
      git:
        repo: '{{ git_repo }}'
        dest: '{{ compound_chain_home }}'
        version: '{{ git_branch }}'
        key_file: '{{ git_deploy_key }}'
        accept_hostkey: yes

    - name: Compile Compound Chain
      command:
        cmd: '{{ cargo_bin }} build --release'
        chdir: '{{ compound_chain_home }}'
