
- hosts: authority_node
  vars:
    compound_chain_home: "{{ ansible_env.HOME }}/compound_chain"
  tasks:        
    - name: install Compound Chain systemd unit file
      template: src=../tmpl/compound-chain-authority-node.j2 dest=/etc/systemd/system/compound-chain.service
      become: true

    - name: start Compound Chain Authority Node
      systemd: state=started name=compound-chain daemon_reload=yes
      become: true

- hosts: full_node
  vars:
    compound_chain_home: "{{ ansible_env.HOME }}/compound_chain"
  tasks:        
    - name: install Compound Chain systemd unit file
      template: src=../tmpl/compound-chain-full-node.j2 dest=/etc/systemd/system/compound-chain.service
      become: true

    - name: start Compound Chain Full Node
      systemd: state=started name=compound-chain daemon_reload=yes
      become: true
