name: Build
on:
  push:
    branches:
      - develop

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build x86_64
        run: |
          set -eo pipefail
          ./scripts/get_substrate.sh --fast
          WASM_BUILD_RUSTFLAGS='--cfg feature="integration"' cargo build --release --features integration

      - uses: actions/upload-artifact@v2
        with:
          name: gateway-x86_64-linux
          path: target/release/gateway
          if-no-files-found: error

  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          set -eo pipefail
          ./scripts/get_substrate.sh --fast
          WASM_BUILD_RUSTFLAGS='--cfg feature="integration"' cargo build --release --features integration

      - uses: actions/upload-artifact@v2
        with:
          name: gateway-x86_64-macos
          path: target/release/gateway
          if-no-files-found: error