name: Build
on:
  push:
    tags:
      - 'm*'

jobs:
  create_release:
    name: Create Empty Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: true
          prerelease: true


  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          set -eo pipefail
          ./scripts/get_substrate.sh --fast
          ./scripts/build_release.sh mRelease

      - name: Upload Release Asset
        id: upload-gateway
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: releases/mRelease
          asset_name: gateway-linux-x64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        id: upload-gateway-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: releases/mRelease
          asset_name: gateway-linux-x64.checksum
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        id: upload-contracts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: releases/mRelease
          asset_name: contracts.json
          asset_content_type: application/json

      - name: Upload Release Asset
        id: upload-types
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: releases/mRelease
          asset_name: types.json
          asset_content_type: application/json

      - name: Upload Release Asset
        id: upload-rpc
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: releases/mRelease
          asset_name: rpc.json
          asset_content_type: application/json

  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          set -eo pipefail
          ./scripts/get_substrate.sh --fast
          ./scripts/build_release.sh mRelease

      - name: Upload Release Asset
        id: upload-gateway-darwin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: releases/mRelease
          asset_name: gateway-darwin-x64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        id: upload-gateway-darwin-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: releases/mRelease
          asset_name: gateway-darwin-x64.checksum
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        id: upload-gateway-wasm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: releases/mRelease
          asset_name: gateway.wasm
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        id: upload-gateway-wasm-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: releases/mRelease
          asset_name: gateway.wasm.checksum
          asset_content_type: application/octet-stream